# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Donation

# Model Form Field configuration
form: $/fuascailtdev/niapays/models/donation/fields.yaml

# Model Class name
modelClass: Fuascailtdev\NiaPays\Models\Donation

# Default redirect location
defaultRedirect: Fuascailtdev/niapays/donation

# Create page
create:
    title: backend::lang.form.create_title
    redirect: Fuascailtdev/niapays/donation/update/:id
    redirectClose: Fuascailtdev/niapays/donation

# Update page
update:
    title: backend::lang.form.update_title
    redirect: Fuascailtdev/niapays/donation
    redirectClose: Fuascailtdev/niapays/donation

# Preview page
preview:
    title: backend::lang.form.preview_title
